---
- name: Test nginx configuration
  listen: Restart nginx
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Reload nginx
  listen: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
