---
- name: Check if ignore-subscription patch is already present
  ansible.builtin.shell: "grep -q '{{ proxmox_patch_tag }}' {{ pve_js_path }}"
  register: patch_present
  ignore_errors: true

# Only run future tasks based on the result of patch_present.
# If patch_present.rc != 0 make the change

- name: Ensure original proxmoxlib.js is backed up (with timestamp)
  ansible.builtin.copy:
    src: "{{ pve_js_path }}"
    dest: "{{ pve_js_path }}.bak.{{ ansible_date_time.iso8601_basic }}"
    remote_src: yes
  when: patch_present.rc != 0
  register: backup_js
  changed_when: backup_js.changed

- name: Inject ignore-subscription patch
  # We will find the place where the check happens
  # checked_command: function(orig_cmd) {     <---- Find this
  #   orig_cmd();                             <---- Add this and...
  #   return;                                 <---- Add this to short circuit check subscription function
  #   Proxmox.Utils.API2Request(
  #       {
  #           url: '/nodes/localhost/subscription',
  #           method: 'GET',
  #           failure: function(response, opts) {
  ansible.builtin.replace:
    path: "{{ pve_js_path }}"
    regexp: '^\s*(checked_command:\s*function\(orig_cmd\)\s*\{)\s*$'
    replace: '\1 {{ proxmox_patch_tag }}\n    orig_cmd(); {{ proxmox_patch_tag }}\n    return; {{ proxmox_patch_tag }}'
    backup: yes
  when: patch_present.rc != 0
  notify: Restart pveproxy

