---
galaxy_info:
  author: Darrick Ross & AI
  description: Disable a select APT repository
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
dependencies: []
