---
- name: "Ensure var 'repo_file' is provided"
  ansible.builtin.assert:
    that:
      - repo_file is defined
      - repo_file | length > 0
    fail_msg: >
      You must supply `repo_file` to proxmox-disable_repo,
      e.g. `vars: repo_file: pve-enterprise.list`

- name: "Stat enterprise repo: '{{ repo_file }}'"
  ansible.builtin.stat:
    path: "{{ pve_apt_sources_dir }}/{{ repo_file }}"
  register: enterprise_repo_stat

- name: "If exists, Rename enterprise repo: '{{ repo_file }}' "
  ansible.builtin.command: >
    mv {{ pve_apt_sources_dir }}/{{ repo_file }}
      {{ pve_apt_sources_dir }}/{{ repo_file }}.disabled
  args:
    removes: "{{ pve_apt_sources_dir }}/{{ repo_file }}"
    creates: "{{ pve_apt_sources_dir }}/{{ repo_file }}.disabled"
  when: enterprise_repo_stat.stat.exists
  notify: Refresh APT cache
