---
# Default variables; override in your playbook as needed
mtu_size: 9000

# Priority level for the interfaces (lower value = higher Priority)
iface_bridge_metric: 100
iface_p2p_metric: 50

# Source/dest of interfaces file
interfaces_dest: /etc/network/interfaces
other_interfaces_src_dir: /etc/network/interfaces.d/*

# Ping test stuff
ping_count: 4
mtu_size_ip_header: 20
mtu_size_icmp_header: 8
ping_payload_size: "{{ (mtu_size - mtu_size_ip_header - mtu_size_icmp_header) }}"

# Host File Mark
peer_host_block_marker_start: "Peer Host Block Start"
peer_host_block_marker_end: "Peer Host Block End"
