hypervisors_proxmox:
  hosts:
    hv00-pve.sol.mw:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/yubikey_sk
    hv01-pve.sol.mw:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/yubikey_sk
