---
- name: Deploy /etc/network/interfaces from template
  become: true
  ansible.builtin.template:
    src: interfaces.j2
    dest: "{{ interfaces_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart networking
    - Ping primary gateway
    - Ping p2p
    - Ping primary gateway with MTU
    - Ping p2p with MTU
