---
# This task is used to initially generate SSH Multiplex connections for each host,
# but serialized.
#
# I use a Yubikey as my SSH key, and it can only handle 1 auth request at a time
# Without this the auth will fail immediately for the second thread to request
# the ssh connection.
#
# So this task "warms up" the ssh multiplex connections that future tasks will
# take advantage of. Allowing future connections to be parallel.
- name: Warm up SSH Multiplex connections
  hosts: hypervisors_proxmox
  gather_facts: false
  serial: 1
  tasks:
    - name: Wait for SSH connection
      ansible.builtin.wait_for_connection:
        timeout: 90

- name: Configure general Proxmox hypervisors
  hosts: hypervisors_proxmox
  become: true

  vars:
    repo_files_to_disable:
      - ceph.list
      - pve-enterprise.list

  tasks:
    - name: Apply Networking settings
      ansible.builtin.include_role:
        name: darrickross.proxmox.networking

    # TODO figure out a better way to handle this without uninstalling and reinstalling grub every time...
    # - name: Ensure GRUB updates the removable EFI loader
    #   ansible.builtin.import_role:
    #     name: darrickross.debian.grub_update_removable

    - name: Disable one enterprise repo at a time
      ansible.builtin.include_role:
        name: darrickross.debian.disable_repo
      loop: "{{ repo_files_to_disable }}"
      loop_control:
        loop_var: repo_file_iter
      vars:
        repo_file: "{{ repo_file_iter }}"

    - name: Set up opensource Repos
      ansible.builtin.import_role:
        name: darrickross.proxmox.enable_opensource_repos

    - name: Ensure Proxmox Version
      ansible.builtin.import_role:
        name: darrickross.proxmox.system_upgrade

    - name: Ignore license popup
      ansible.builtin.import_role:
        name: darrickross.proxmox.ignore_license_popup

    - name: Set up Proxmox 443 Proxy using nginx
      ansible.builtin.import_role:
        name: darrickross.proxmox.nginx_proxy

    - name: Set up unattended upgrades
      ansible.builtin.import_role:
        name: darrickross.proxmox.unattended_upgrades
