---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure nginx is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Deploy Proxmox reverse-proxy config
  ansible.builtin.template:
    src: proxmox.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Enable Proxmox site
  ansible.builtin.file:
    src: "{{ nginx_conf_path }}"
    dest: "{{ nginx_conf_enabled }}"
    state: link
  notify: Restart nginx

- name: Test nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Reload nginx if config is OK
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_test.rc == 0
